{{- if .Values.cluster.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "nginx.fullname" . }}
  labels:
    app: {{ template "nginx.name" . }}
    chart: {{ template "nginx.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
{{- if .Values.cluster.slaveCount }}
  replicas: {{ .Values.cluster.slaveCount }}
{{- end }}
  template:
    metadata:
      labels:
        release: "{{ .Release.Name }}"
      {{- if (.Values.slave.podAnnotations | default .Values.master.podAnnotations) }}
      annotations:
{{ toYaml (.Values.slave.podAnnotations | default .Values.master.podAnnotations) | indent 8 }}
      {{- end }}
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
        {{- end}}
      {{- end}}
      {{- /* Include master securityContext if slave securityContext not defined */ -}}
      {{ include "nginx.slave.securityContext" . | indent 6 }}  }
      {{- if (.Values.slave.tolerations | default .Values.master.tolerations) }}
      tolerations:
{{ toYaml (.Values.slave.tolerations | default .Values.master.tolerations) | indent 8 }}
      {{- end }}
      containers:
      - name: {{ template "nginx.fullname" . }}
        image: {{ template "nginx.image" . }}
{{- end }}
